# Generated by Django 5.2 on 2025-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('food', 'Food'), ('home', 'Home'), ('gaming', 'Gaming')], unique=True),
        ),
    ]
